---
- hosts: localhost
  connection: localhost
  vars:
   volume_id: "vol-09278e7dd2fe1249a"
  tasks:
- name: collect the instance index.html
  uri:
   uri: http://169.254.169.254/latest/meta-data/instance-id
   return_content: yes
  register: instance_id
- name: Attach existing EBS
  ec2_vol:
   instance: "{{ instance_id.content }}"
   id: "{{ volume_id }}"
   device_name: /dev/xvdf
   region: " us-east-1"
- name: Mount the volume
  mount:
   path: /var/www/html
   src: /dev/xvdf
   fstype: ext4
   opts: defaults
   state: mounted 